name: Python Package Linux

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black pytest mypy
    - name: Code formatting
      run: |
        black --check gazepy
    - name: Test with pytest
      run: |
        pytest
    - name: Test with mypy
      run: |
        mypy gazepy
